import { Boss } from './boss'
import { BossesPerZone } from './bosses-per-zone'
import { CharactersConfiguration } from './characters-configuration'
import { Classe } from './classe'
import { FavoriteStrategy } from './favorite-strategy'
import { Follow } from './follow'
import { Image } from './image'
import { Skill } from './skill'
import { Strategy } from './strategy'
import { Team } from './team'
import { Toy } from './toy'
import { User } from './user'
import { Vote } from './vote'
import { Zone } from './zone'

export const models: any[] = [Boss,BossesPerZone,CharactersConfiguration,Classe,FavoriteStrategy,Follow,
    Image,Skill,Strategy,Team,Toy,User,Vote,Zone];

export * from './boss'
export * from './bosses-per-zone'
export * from './characters-configuration'
export * from './classe'
export * from './favorite-strategy'
export * from './follow'
export * from './image'
export * from './skill'
export * from './strategy'
export * from './team'
export * from './toy'
export * from './user'
export * from './vote'
export * from './zone'
    