import { ActivationComponent } from './activation/activation.component'
import { AddStrategieComponent } from './add-strategie/add-strategie.component'
import { AdminStratComponent } from './admin-strat/admin-strat.component'
import { AdminUsersComponent } from './admin-users/admin-users.component'
import { ChangerPasswordComponent } from './changer-password/changer-password.component'
import { ClasseComponent } from './classe/classe.component'
import { ContactComponent } from './contact/contact.component'
import { HomeComponent } from './home/home.component'
import { InscriptionComponent } from './inscription/inscription.component'
import { JouetsComponent } from './jouets/jouets.component'
import { ListBossComponent } from './list-boss/list-boss.component'
import { MesInfosComponent } from './mes-infos/mes-infos.component'
import { MesPreferencesComponent } from './mes-preferences/mes-preferences.component'
import { PaginatorComponent } from './paginator/paginator.component'
import { RetrievePasswordComponent } from './retrieve-password/retrieve-password.component'
import { RgpdComponent } from './rgpd/rgpd.component'
import { SearchStrategieComponent } from './search-strategie/search-strategie.component'
import { SkillsComponent } from './skills/skills.component'
import { TestComponent } from './test/test.component'

export const components:any[] = [ActivationComponent,AddStrategieComponent,AdminStratComponent,AdminUsersComponent,ChangerPasswordComponent,
                                ClasseComponent,ContactComponent,HomeComponent,InscriptionComponent,JouetsComponent,ListBossComponent,
                                MesInfosComponent,MesPreferencesComponent,PaginatorComponent,RetrievePasswordComponent,RgpdComponent,
                                ,SearchStrategieComponent,SkillsComponent,TestComponent]

export * from './activation/activation.component'
export * from './add-strategie/add-strategie.component'
export * from './admin-strat/admin-strat.component'
export * from './admin-users/admin-users.component'
export * from './changer-password/changer-password.component'
export * from './classe/classe.component'
export * from './contact/contact.component'
export * from './home/home.component'
export * from './inscription/inscription.component'
export * from './jouets/jouets.component'
export * from './list-boss/list-boss.component'
export * from './mes-infos/mes-infos.component'
export * from './mes-preferences/mes-preferences.component'
export * from './paginator/paginator.component'
export * from './retrieve-password/retrieve-password.component'
export * from './rgpd/rgpd.component'
export * from './search-strategie/search-strategie.component'
export * from './skills/skills.component'
export * from './test/test.component'